kind: pipeline # 定义对象类型，还有secret和signature两种类型
type: docker # 定义流水线类型，还有kubernetes、exec、ssh等类型
name: drone-build # 定义流水线名称

steps: # 定义流水线执行步骤，这些步骤将顺序执行
  - name: build-web # 流水线名称
    image: ruby:3.0 # 定义创建容器的Docker镜像
    commands: # 定义在Docker容器中执行的shell命令
      - gem install bundler:2.4.18
      - bundle install # 安装依赖
      - jekyll build # 打包

  - name: master_build
    image: cschlosser/drone-ftps
    environment:
      FTP_USERNAME:
        from_secret: ftpusername
      FTP_PASSWORD:
        from_secret: ftppassword
      PLUGIN_HOSTNAME: 
        from_secret: ftphost

      PLUGIN_SRC_DIR: ./_site/
      PLUGIN_SECURE: false
      PLUGIN_VERIFY: false

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
